### PR TITLE
[D] initial commit for graphqld

### PR DESCRIPTION
**Pull request by cyrusmsk**
I've added initial implementation for graphqld.
Also updated run.cr and shell.nix.

But not sure where I need to put how to run executable file.

### CODE REVIEW

**Comment by cyrusmsk** [comment]
@jgillich it seems the problem is in Nimble NixOS package..

**Comment by jgillich** [comment]
Please rebase, the nimble problem is fixed now.

**Comment by cyrusmsk** [comment]
> Please rebase, the nimble problem is fixed now.

Done

**Comment by jgillich** [comment]
Apologies, this looks good. Is there any way to get rid of the following warning and all the log spam below it?

```
Warning (thread: main): leaking eventcore driver because there are still active handles
```

**Comment by cyrusmsk** [comment]
> Is there any way to get rid of the following warning and all the log spam below it?
> 
> ```
> Warning (thread: main): leaking eventcore driver because there are still active handles
> ```

Hard to tell..
The issue is quite old.. and it seems still happening from time to time https://github.com/vibe-d/vibe.d/issues/2245
I've added suggested solution - but I'm not sure it will fix the issue.

**Comment by jgillich** [comment]
It could probably be hidden with `setLogLevel(LogLevel.Error);`, right? https://vibed.org/api/vibe.core.log/setLogLevel

**Comment by jgillich** [comment]
`dub --quiet` would be nice too

**Pull request merged**
